# Generated by Django 3.2.9 on 2023-07-22 11:45

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('image', models.ImageField(default='default.jpg', upload_to=profiles.models.get_profile_image_path)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
