# Generated by Django 3.2.9 on 2023-10-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_picture', models.ImageField(blank=True, upload_to='')),
                ('event_date', models.DateField(blank=True)),
                ('event_time', models.TimeField(blank=True)),
                ('event_description', models.TextField(max_length=200)),
            ],
        ),
    ]
